site:
    title: AsciiDoc Linter Documentation
    start_page: linter::index.adoc
    url: https://testthedocs.github.io/asciidoc-linter
content:
    sources:
      - url: ../../
        branches: [ HEAD ]
        start_path: packages/website/src
ui:
    bundle:
        url: ../theme/dist
        snapshot: true
asciidoc:
    attributes:
        source-highlighter: highlight.js
        idprefix: ''
        idseparator: '-'
        experimental: ''
        page-pagination: '@'
        tabs-sync-option: ''
        lang: en
        figure-caption!: ''
        table-caption!: ''

    extensions:
      - '@asciidoctor/tabs'

antora:
  extensions:
    - '@antora/lunr-extension'

output:
    dir: ./build/site
